name: Node

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'client/package.json'
      - 'client/package-lock.json'
      - 'client/tsconfig.json'
      - 'client/**.js'
      - 'client/**.ts'
      - 'client/**.vue'
  push:
    branches:
      - main
      - master

permissions:
  contents: read

concurrency:
  group: node-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    name: node
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v2 # v2.1
        id: versions
        with:
          fallbackNode: '^18'
          fallbackNpm: '^9'
          path: "./client"

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: cd client && npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install dependencies & build
        run: |
          cd client
          npm ci
          npm run build --if-present

      - name: Check webpack build changes
        run: |
          cd client
          bash -c "[[ ! \"`git status --porcelain `\" ]] || (echo 'Please recompile and commit the assets, see the section \"Show changes on failure\" for details' && exit 1)"

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention
